name: Build & Publish

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags for this build'

jobs:
  publish:
    name: Build, Test, Pack & Release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish NuGet
      id: publishNuGet
      uses: alirezanet/publish-nuget@v3.1.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/OpenLayers.Blazor/OpenLayers.Blazor.csproj
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: SpatialFocus.OpenLayers.Blazor
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true
        # Format of the git tag, [*] gets replaced with actual version
        TAG_FORMAT: build_*
        VERSION_STATIC: 0.1.1
    - name: Persist NuGet artifact
      uses: actions/upload-artifact@v1
      if: ${{steps.publishNuGet.outputs.PACKAGE_NAME != ''}}
      with:
        name: ${{steps.publishNuGet.outputs.PACKAGE_NAME}}
        path: ${{steps.publishNuGet.outputs.PACKAGE_PATH}}
    - name: Persist SNuGet artifact
      uses: actions/upload-artifact@v1
      if: ${{steps.publishNuGet.outputs.SYMBOLS_PACKAGE_NAME != ''}}
      with:
        name: ${{steps.publishNuGet.outputs.SYMBOLS_PACKAGE_NAME}}
        path: ${{steps.publishNuGet.outputs.SYMBOLS_PACKAGE_PATH}}
